project:
  type: website

website:
  title: "Flow Cytometry Analysis using R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Workshop
        menu:
        - text: "Basics of working with FCS files"
          href: vignettes/1_Import_fcs.html
        - text: "Spillover, compensation, and Transformations"
          href: vignettes/2_Spillover_transformation.html
        - text: "Gating Cells"
          href: vignettes/3_Gating_1.html  
        - text: "Accessing gated data"
          href: vignettes/4_Gating_2.html
        - text: "Gating cells with gatingTemplates"
          href: vignettes/5_Gating_gatingTemplate.html
        - text: "Visualizations using ggcyto"
          href: vignettes/6_ggcyto.html
        - text: "Reporting"
          href: vignettes/7_Reporting.html
format:
  html:
    theme: 
      - cerulean
      - utils/css/custom.scss
    toc: true
    toc-expand: 1
    toc-title: Contents
    embed-resources: true
    css: utils/css/custom.css
    smooth-scroll: true


