project:
  type: website
  output-dir: docs

website:
  title: "Flow Cytometry Analysis using R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Workshop
        menu:
        - text: "Basics of working with FCS files"
          href: vignettes/1_Import_fcs.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



